language: java

# any more recent ubuntu image doesnt have java 8
dist: trusty

jdk: oraclejdk8

env:
  global:
    # these secure values are encrypted for linkedin/avro-util. for use in forked repos, set env vars in your own build - they should win over these (as these wont be decodable in forked builds)
    - secure: "eO+ZePMAmkXFwfcNFnGX13sF13KnxubY9S+iyOn4XzyBFtO5KQD5J80yL9V9D46LRz4T87Jz/Fww2Wy2eGlFMJl862cTN3S2oT6QNsNLxYrehD2lhetLY9+nW33op6epiC/XUi+PX0vO1SPTx+IxmiVQX9d2JnplyTMsDb/A/S4pBBSZQFhWKwy8zSZ6V1hYPE7Lmjbu5tWNo2H03gSM+ktW+Z8MDZ1Tv+ngYtUjnFjtU255CpFAZ1cq1tPF6tRW5vXNFji2igtVGGpqeqMvmd+1oQMFd+XbmafdIdv0zUw2dGVYzk7lUd0sN5fC2MhK3g8RnQ5O3SHKnY2pC406yqYVVl85Ct8JxsLWt3+oOgKzlLpaT7dUK1bIHnInmL4adnxzO//Q90m+qEPhxMpF3bPcLI8eKAsn28TEzevA+iFuxRJGsPniBWlaUJgk4+A5E3qXO753NYNkkkNHAdbOnpttmKWjpKhfAJU32rNCVG/YWWhFtnxeR25lM1SuusJPcwd99WcP2YwSYObIm4a5dWO6I1SkIx3wPYh5L7a3FqHfJ99R2V5N1YaJQk7bmdH1mypQ5q8jf88TXdsKgc6tN++I3GjIv8qZ3dd+tmwwZmXfv9wddGuMIuzWYjmp8z8dDj5aalUfVPtzk+KXJxvYcvkXaTwaSwUPWuLVKd4WfUU="
    - secure: "SX7B/ghnv07MblAyzcLH3P/eBqZaovFpYau968hLPLK4S7OC2huO+gsWVlG7eEo6JxKQkt6F/kmEgNK/My0vqopXLjQGw5Qci/bnYl3/JpjnIPJ95a25LWATXWoJI5BjEdyiEXFpWsgvq697X4xx/Vc3xl15IM2G73yG4ahVDFXCAg10GXfzCn12yESDCoa2zPLzfVnu7UXkP8+TB61iFoVcRFBmQbuqGJbIRcb5VHTjygm1w5DKuSqDg9FYuwGCYhspEJwfETlXwDWO17U0AbrxIcCI7S5Q3pNDrIazBiDTFMuInvQ8XfQHIx1ec1bNNS3dC8ocwGLgXpabhbguRtDEhnpLuFIzZFrOWzAk9vIzUpAGmHrP+eDKXhdVSs39Iwwkbm8VYRHo9Y49AYjAaIDJuTVPGHeIZbIEeVZdKkM6/7C7/nynYDR4s3vMmGCJnxriv3538XJH5cIc5RSOwKhmm8Xfqpqc36U8qfLxASI+RyLX9Di2yz4F5qmCtqMIEuPa8P3lIWBb1neqxzQucBxPHSUSEpI9afPQZUukqt5L3ElsyZ5ZCmXKD0i1+03xquHPMb9kncxAYfz8GdWG/ijKPwtv0WuVqlizkcbG1DQzYgQRQN6+QC4Odt1PPp23HEHBJJxcw7fnPMIMLQOHk72s9tjTViuQJOp3HkcW8w4="

# update to latest oracle jdk8 (adds ~20 seconds)
addons:
  apt:
    packages:
      - oracle-java8-installer

# instead of the default install step (./gradlew assemble) just fetch our wanted gradle version
install: true

script:
  - ./gradlew clean build javadoc --no-daemon

# required for gradle artifact caching (see https://docs.travis-ci.com/user/languages/java/#caching)
before_cache:
  - rm -rvf $HOME/.gradle/caches/journal-*/file-access.bin
  - rm -rvf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rvf $HOME/.gradle/caches/*/scripts/
  - rm -rvf $HOME/.gradle/caches/*/*.lock
  - sync

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  provider: script
  script: bash -v scripts/publishToBintray.sh
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    # the condition on the tag name (should be a semantic version) is inside the script, for ease of development
