/*
 * Copyright 2018 LinkedIn Corp.
 * Licensed under the BSD 2-Clause License (the "License"). 
 * See License in the project root for license information.
 */

package com.acme.generatedbylatest;
//this is code generated by the migration helper running under 1.8 with the compatibility option
@SuppressWarnings("all")
// @org.apache.avro.specific.AvroGenerated
public enum EnumType {
  A, B, C  ;
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"enum\",\"name\":\"EnumType\",\"namespace\":\"com.acme\",\"symbols\":[\"A\",\"B\",\"C\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
