/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.acme;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class HasUnions17 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HasUnions\",\"namespace\":\"com.acme\",\"fields\":[{\"name\":\"f1\",\"type\":[\"null\",\"HasUnions\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public HasUnions f1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HasUnions17() {}

  /**
   * All-args constructor.
   */
  public HasUnions17(HasUnions f1) {
    this.f1 = f1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return f1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: f1 = (HasUnions)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f1' field.
   */
  public HasUnions getF1() {
    return f1;
  }

  /**
   * Sets the value of the 'f1' field.
   * @param value the value to set.
   */
  public void setF1(HasUnions value) {
    this.f1 = value;
  }

  /** Creates a new HasUnions RecordBuilder */
  public static HasUnions.Builder newBuilder() {
    return new HasUnions.Builder();
  }
  
  /** Creates a new HasUnions RecordBuilder by copying an existing Builder */
  public static HasUnions.Builder newBuilder(HasUnions.Builder other) {
    return new HasUnions.Builder(other);
  }
  
  /** Creates a new HasUnions RecordBuilder by copying an existing HasUnions instance */
  public static HasUnions.Builder newBuilder(HasUnions other) {
    return new HasUnions.Builder(other);
  }
  
  /**
   * RecordBuilder for HasUnions instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HasUnions>
    implements org.apache.avro.data.RecordBuilder<HasUnions> {

    private HasUnions f1;

    /** Creates a new Builder */
    private Builder() {
      super(HasUnions.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(HasUnions.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing HasUnions instance */
    private Builder(HasUnions other) {
            super(HasUnions.SCHEMA$);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'f1' field */
    public HasUnions getF1() {
      return f1;
    }
    
    /** Sets the value of the 'f1' field */
    public HasUnions.Builder setF1(HasUnions value) {
      validate(fields()[0], value);
      this.f1 = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'f1' field has been set */
    public boolean hasF1() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'f1' field */
    public HasUnions.Builder clearF1() {
      f1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public HasUnions build() {
      try {
        HasUnions record = new HasUnions();
        record.f1 = fieldSetFlags()[0] ? this.f1 : (HasUnions) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
